### ISSUE TITLE
Fix error-page exceptions

### ISSUE THREAD

**Issue by cesguerra** [ziplet/ziplet#28]
Hi

We have some error pages in our application that were working well:

    <error-page>
        <error-code>404</error-code>
        <location>/WEB-INF/jsp/error-pages/notfound.jsp</location>
    </error-page>
    <error-page>
        <error-code>500</error-code>
        <location>/WEB-INF/jsp/error-pages/internalserver.jsp</location>
    </error-page>

Our CompressingFilter configuration:

    <filter>
        <filter-name>compressingFilter</filter-name>
        <filter-class>com.github.ziplet.filter.compression.CompressingFilter</filter-class>
        <init-param>
            <param-name>includeContentTypes</param-name>
            <param-value>application/javascript,application/json,application/xml,text/css,text/html,text/javascript,text/plain,text/xml</param-value>
        </init-param>
    </filter>    
    <filter-mapping>
        <filter-name>compressingFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

**I think the problem is that CompressingFilter write/close the output stream even with http error codes.**

Here I forced an http 404:

2017-09-05 10:53:35 ERROR -> [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost]] Exception Processing ErrorPage[errorCode=404, location=/WEB-INF/jsp/error-pages/notfound.jsp]
org.apache.jasper.JasperException: **java.lang.IllegalStateException: getOutputStream() has already been called for this response**
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:521)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:409)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:336)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:265)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:654)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:447)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:379)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:292)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:423)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:342)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:157)
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:393)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:262)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:446)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at org.apache.catalina.connector.Response.getWriter(Response.java:604)
        at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:198)
        at org.apache.jasper.runtime.JspWriterImpl.initOut(JspWriterImpl.java:125)
        at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:118)
        at org.apache.jasper.runtime.PageContextImpl.release(PageContextImpl.java:186)
        at org.apache.jasper.runtime.JspFactoryImpl.internalReleasePageContext(JspFactoryImpl.java:117)
        at org.apache.jasper.runtime.JspFactoryImpl.releasePageContext(JspFactoryImpl.java:76)
        at org.apache.jsp.WEB_002dINF.jsp.error_002dpages.notfound_jsp._jspService(notfound_jsp.java:129)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:373)
        ... 21 more

**Comment by cesguerra** [comment]
I'm using the old Jboss 4.2.3 (http://jbossas.jboss.org/downloads) for compatibility reasons.
