### ISSUE TITLE
java.lang.AssertionError in CompressingServletOutputStream.abortCompression

### ISSUE THREAD

**Issue by chaostya** [ziplet/ziplet#5]
1. get response.getOutputStream()
2. don't write to it anything
3. set forbidden (in web.xml filter config) content type header e.g. response.setContentType("application/pdf");
4. add another header that would abort compression like response.addHeader("Cache-Control", "no-transform, max-age=3600");

Boom:
java.lang.AssertionError
        at com.github.ziplet.filter.compression.CompressingServletOutputStream.abortCompression(CompressingServletOutputStream.java:120)
        at com.github.ziplet.filter.compression.CompressingHttpServletResponse.maybeAbortCompression(CompressingHttpServletResponse.java:195)
        at com.github.ziplet.filter.compression.CompressingHttpServletResponse.addHeader(CompressingHttpServletResponse.java:108)

and then Weblogic says:
java.net.ProtocolException: Didn't meet stated Content-Length, wrote: '0' bytes instead of stated: '3750917' bytes.
        at weblogic.servlet.internal.ServletOutputStreamImpl.ensureContentLength(ServletOutputStreamImpl.java:446)
        at weblogic.servlet.internal.ServletResponseImpl.ensureContentLength(ServletResponseImpl.java:1432)
        at weblogic.servlet.internal.ServletResponseImpl.send(ServletResponseImpl.java:1511)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1462)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:209)

and response goes back to the client with empty body

**Comment by benjamin-bader** [comment]
I'm hitting this while using Spring Boot - i.e. I am not in control of the order of operations.  What options do I have to avoid/fix this bug?

I assume that the assertion exists for a reason, and that to simply remove it would invite problems?

**Comment by yblpub** [comment]
It seems to be a mismatch in the assertion expression replace "== null" by "!= null".
Code says:
```
    void abortCompression() throws IOException {
        assert thresholdOutputStream == null;        // line 120
        checkWriteState();
        thresholdOutputStream.forceOutputStream1();  // inconsistent with assertion: will fail if null
        aborted = true;
    }
```

**Comment by blasd** [comment]
Just in case, a unit-test based over Spring:

	@Test
	public void testGetBodyThenWrite() throws HttpMessageNotWritableException, IOException, ServletException {
		HttpServletResponse httpResponse = Mockito.mock(HttpServletResponse.class);
		Mockito.when(httpResponse.getOutputStream()).thenReturn(Mockito.mock(ServletOutputStream.class));

		CompressingStreamFactory compressingStreamFactory = Mockito.mock(CompressingStreamFactory.class);
		String contentEncoding = "contentEncoding";

		FilterConfig filterConfig = Mockito.mock(FilterConfig.class);
		Mockito.when(filterConfig.getInitParameter("includeContentTypes")).thenReturn("false");
		
		ServletContext servletContext = Mockito.mock(ServletContext.class);
		Mockito.when(filterConfig.getServletContext()).thenReturn(servletContext);

		CompressingFilterContext context = new CompressingFilterContext(filterConfig);
		CompressingHttpServletResponse response =
				new CompressingHttpServletResponse(httpResponse, compressingStreamFactory, contentEncoding, context);
		response.setContentType(MediaType.IMAGE_JPEG.getType());

		HttpOutputMessage outputMessage = Mockito.mock(HttpOutputMessage.class);
		Mockito.when(outputMessage.getBody()).then(invok -> response.getOutputStream());
		Mockito.when(outputMessage.getHeaders()).thenReturn(new HttpHeaders());

		Resource resource = new InMemoryResource("Youpi");
		new ResourceHttpMessageConverter().write(resource, MediaType.ALL, outputMessage);
	}

**Comment by alarive** [comment]
I ran into this issue too while writing Spring Boot tests.

This error happens when CompressingHttpServletResponse.getOutputStream gets called two times (which Spring does) and the stream should not be compressed.

@yblpub : thresholdOutputStream.forceOutputStream1() will not fail since checkWriteState() is responsible for initiliazing thresholdOutputStream.

My opinion is that this assertion should simply be deleted.

**Comment by alarive** [comment]
As a workaround, I set the compressionThreshold to 0, which has the effect of compressing everything.

**Comment by MateuszStefek** [comment]
Is there any update on the issue?

**Comment by johanhaleby** [comment]
I run into the same issue. Setting `compressionThreshold` to 0 seems to fix it but this is not optimal.
